# Generated by Django 2.1.4 on 2020-03-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200312_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
    ]
